### ISSUE TITLE
Problem with draft ebvnc

### ISSUE THREAD

**Issue by justinoverton** [joostdecock/site#339]
See [here](https://freesewing.org/drafts/ebvnc)

The comparison looks quite different, but I typed in the measurements correctly. it's quite possible I measured incorrectly, but I took measurements based on the diagrams and descriptions.

Is there any measurement that appears "obviously wrong"?

**Comment by joostdecock** [comment]
I don't think there's a problem here. Your torso seems a bit shorter than our set of standard measurements, but that's nothing to worry about.

Apart from that, I don't see anything suspicious. It's because the comparison is anchored at the bottom that they seem very different, but they're really just a bit shorter.

If you have a look at the yoke + back (which is anchored at the top) you can see it's just shorter, but apart from that pretty standard.

Unless you have reason to believe you mis-measured your torso length, I think you'll be fine 👍

(Edited to fix a typo)
