### ISSUE TITLE
PDFs for draft are blank in all sizes except full

### ISSUE THREAD

**Issue by apostrophes** [joostdecock/site#415]
While I encountered this issue on pvbxk in the screenshot, it occurs on every draft I've tried. [(example draft)](https://freesewing.org/drafts/vurwp)
Also, the letter and tabloid PDF files do not have the ".pdf" extension and instead are simply ".letter" and ".tabloid"

<img width="1106" alt="screen shot 2018-05-25 at 11 05 13 pm" src="https://user-images.githubusercontent.com/39636205/40572025-afedcce4-6070-11e8-9f1e-4f785ddd6241.png">

**Comment by apostrophes** [comment]
Actually, did I miscategorize this one? I have no idea if it's a core bug or a site bug

**Comment by joostdecock** [comment]
This is probably a data bug :wink:

**Comment by joostdecock** [comment]
Turns out this was caused by a broken [tile](https://github.com/freesewing/tile) install.

@woutervdub I compiled tile from source on the new server, based on the latest in the repo.
Seems that that didn't do the trick, so I've copied over the binary from our other server for now and that works.

We'll have to look into this at some point, but for now I am going to focus on the open issues here in site.
