### ISSUE TITLE
User doesn't exist page

### ISSUE THREAD

**Issue by AlfaLyr** [joostdecock/site#508]
https://freesewing.org/users/whateveruser shows a profile which says "has been with us since 48 years ago" if whateveruser doesn't exist, instead of something like "this user does't exist".

Really sorry to bring the issues number up to 2 digits again!

**Comment by joostdecock** [comment]
Even if you pushed the number of issues to 3 digits, I wouldn't mind. As long as we fix things or make improvements, we're doing good work.

So thanks for reporting this, I've fixed it. However, since this needed changes in both front and backend, it won't show up until those backend changes are deployed (ongoing)

**Comment by AlfaLyr** [comment]
Good :)
(I discovered it assigning the new translator badge :P)

**Comment by joostdecock** [comment]
Cool :) that reminds me, all people listed here should get that badge: https://freesewing.org/i18n/

**Comment by AlfaLyr** [comment]
ahead of you :P
