### ISSUE TITLE
Unable to sign up

### ISSUE THREAD

**Issue by tomtom1967** [joostdecock/site#620]
I'm trying to sign up but did nor receive a confirmation in my mail.
At closer inspection of the console log during the signup I see there is a Error: "Request failed with status code 400"

Apparently there is an exception at:
```
              signup: function (e) {
                return new p.a(function (t, n) {
                  m.data.post('/signup', e).then(function (e) {
                    T(e.data.token),
                    t(e.data)
                  }).catch (function (e) {
                    console.log(e),
                    n(e)
                  })
                })
              },
```
But before that there are a bunch of other javascript errors. See picture.
![freesewingjavascripterror](https://user-images.githubusercontent.com/831466/46206640-e8656c00-c324-11e8-8a7e-1cd61f7f8b3f.png)

If there is any thing I can do to help you fixt this just let me know.

Regards,
Thomas

**Comment by joostdecock** [comment]
An issue from someone who includes console info? Wow, this is a real treat :)

The errors are about the referral logging. I should look into that, but it's not causing the issue.
You didn't receive the email because outgoing email were queued due to an unrelated issue.

I've fixed the issue, the outgoing email queue has been cleared, so you will have a bunch of emails in your inbox as I see you tried more than once :)

Sorry about that. Activate your account via the link in the confirmation message, and everything should be ok.
