### ISSUE TITLE
Patterns fail to generate

### ISSUE THREAD

**Issue by flaminSaganaki** [joostdecock/site#630]
When trying to generate a Theodore or Theo pattern it shows a "something went wrong" message. Doesn't show details on the website, need to check the internal logs.

**Comment by joostdecock** [comment]
Thanks for reporting this. Can you provide your username, or the reference of the model you're drafting this for?

The url of the draft page contains this info.

Tx

**Comment by flaminSaganaki** [comment]
Username is tjmavrakis
Here is the url:
https://freesewing.org/draft/theo/for/fdnet
I suppose “fdnet” is the reference to the model. I also tried it with another model “ypqzx” and it didn’t work either.

Cheers,
Theodore

________________________________

**Comment by joostdecock** [comment]
That's correct, thank you. I am queueing to board a plane, but I will look into this later today.

**Comment by joostdecock** [comment]
It seems you are mixing up inches and cm. I checked your model, and it has a hip circumference of 33cm.
I assume that is supposed to be 33 inch, and that's why things go wrong.

I've taken the liberty of changing your units for you (but in case you're wondering, go to your account, you can change the settings there). 

You can draft Theo(dore) again, you'lll see that it works now.
