### ISSUE TITLE
Failed to draft Carlton for model Leo @leoqian200218

### ISSUE THREAD

**Issue by MostSmartest** [joostdecock/site#652]
First time drafting a pattern so unsure where exactly the issue might be. Thank you!!!

**Comment by joostdecock** [comment]
You have a shoulder slope of 40cm. I assume that's a typo because that's impossible.

I've changed it to 4cm, and drafted Carlton for you, it looks fine: https://freesewing.org/drafts/xagwu

If it wasn't a typo, please check the documentation for the shoulder slope measurement: https://freesewing.org/docs/measurements/shoulderslope
